[simulation]
command = "./sim-lola -f -n -c ../../data/noisytest/conf/forceControlHighGain.conf -p 1"
note = "+simulated jump in right foot's vertical force by 400N (to lower forces)."

[data]
chunk_ranges = [[2.08, 2.14], [2.291, 2.322], [2.593, 2.619], [3.697, 3.715], [3.896, 3.926], [5.298, 5.316], [5.497, 5.514], [5.793, 5.827], [6.897, 6.914], [7.097, 7.112], [7.391, 7.424], [8.495, 8.512], [8.696, 8.708]]
chunk_labels = ["highaccelerations", "highaccelerations", "oscillations", "highaccelerations", "highaccelerations", "highaccelerations", "highaccelerations", "oscillations", "highaccelerations",  "highaccelerations", "oscillations",  "highaccelerations",  "highaccelerations"]