[simulation]
command = "./sim-lola -f -n -c ../../data/noisytest/conf/repeatedEarlyContact.conf -p 1 -e 15"

[data]
chunk_ranges = [[6.16, 6.28], [7.26, 7.33], [7.77, 7.86], [8.86, 8.91], [9.37, 9.50], [10.44, 10.57]]
chunk_labels = ["impact", "impact", "impact", "impact", "impact", "impact"]